driverClassName: org.h2.Driver
logging:
    level:
        org:
            springframework:
                web: TRACE
        web: TRACE
password: sa
server:
    port: 8089
spring:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
url: jdbc:h2:mem:mydb
username: sa
